# Don't change this file, it's the default config file. Instead, please edit
# /etc/nodeftpd.yml

listen: '%default_ip%'
port: 21
socket: /var/run/nodeftpd.sock
pid_file: /var/run/nodeftpd.pid
logging:
  error_log: /var/log/nodeftpd/error.log
  access_log: /var/log/nodeftpd/access.log
passive_port_range: 40000-60000
motd: 'NodeFTPD %pkg.version% Server (%os.hostname%)'
auth:
  provider: pam
  default_chroot: '~'
tls:
  enabled: false
  key: ''
  cert: ''
  port: 990
